/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** the computed board, rebuilt from a fresh read of the disk */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** capture a new item into inbox */
        post: operations["createItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: components["parameters"]["filename"];
            };
            cookie?: never;
        };
        /** one item's raw content and parsed card */
        get: operations["getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{filename}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: components["parameters"]["filename"];
            };
            cookie?: never;
        };
        get?: never;
        /** raw save; a state-changing save runs the ranked-transition cleanup */
        put: operations["saveContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{filename}/state": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: components["parameters"]["filename"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** transition, or transition-and-place when position is given */
        post: operations["transitionItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/{lane}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lane: components["schemas"]["state"];
            };
            cookie?: never;
        };
        get?: never;
        /** rewrite one lane's ranked prefix */
        put: operations["reorderLane"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{filename}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: components["parameters"]["filename"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** remove an item file — the operator's explicit curation gesture. the item's order.yaml entries go in the same gesture. */
        post: operations["deleteItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{filename}/retitle": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: components["parameters"]["filename"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** retitle and rename to the new slug, rank preserved */
        post: operations["retitleItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{filename}/rename-to-slug": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: components["parameters"]["filename"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** repair the filename-mismatch flag with one rename */
        post: operations["renameToSlug"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        state: "inbox" | "horizon" | "researching" | "building" | "evaluating" | "done" | "dropped";
        flag: {
            /** @enum {string} */
            kind: "malformed" | "filename-mismatch";
            diagnostic: string;
        };
        logEntry: {
            stamp: string;
            note: string;
        };
        card: {
            filename: string;
            /** @description empty when the title could not be read; show the filename. */
            title: string;
            /** @description absent when state could not be read; the lane carries the effective placement. */
            state?: components["schemas"]["state"];
            created?: string;
            tags?: string[];
            /** @description parts of the stack this item impacts; most projects don't use them. */
            subsystems?: string[];
            source?: string;
            milestone?: string;
            log?: components["schemas"]["logEntry"][];
            flags: components["schemas"]["flag"][];
            hash: string;
        };
        lane: {
            state: components["schemas"]["state"];
            cards: components["schemas"]["card"][];
            /** @description the first rankedCount cards are the lane's ranked prefix; the rest are the computed unranked tail. */
            rankedCount: number;
        };
        board: {
            /** @description the discovered workspace root's name. */
            project: string;
            lanes: components["schemas"]["lane"][];
            /** @description order.yaml's hash, or the sentinel "absent". absence is a version. */
            orderVersion: string;
        };
        itemLanded: {
            filename: string;
            board: components["schemas"]["board"];
        };
        conflict: {
            /** @enum {string} */
            reason: "item_conflict" | "order_conflict" | "slug_collision";
            message: string;
            /** @description capture collisions; the preserved .capture- draft. */
            tempPath?: string;
            /** @description retitle and rename collisions; the surviving source file. */
            sourcePath?: string;
            /** @description the colliding destination. */
            destPath?: string;
        };
        errorResponse: {
            message: string;
        };
    };
    responses: {
        /** @description the board after the mutation, rebuilt from disk truth */
        freshBoard: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["board"];
            };
        };
        /** @description guard refusal. item_conflict and order_conflict mean the view went stale — reload. slug_collision is a no-clobber refusal and carries structured recovery paths. */
        conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["conflict"];
            };
        };
        /** @description the request fails prevalidation; nothing was written */
        validationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["errorResponse"];
            };
        };
        /** @description repository-level failure */
        serverError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["errorResponse"];
            };
        };
    };
    parameters: {
        filename: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description lanes in lifecycle order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["board"];
                };
            };
            default: components["responses"]["serverError"];
        };
    };
    createItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    body?: string;
                };
            };
        };
        responses: {
            /** @description captured */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["itemLanded"];
                };
            };
            400: components["responses"]["validationError"];
            409: components["responses"]["conflict"];
            default: components["responses"]["serverError"];
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: components["parameters"]["filename"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        content: string;
                        card: components["schemas"]["card"];
                        hash: string;
                    };
                };
            };
            /** @description no such item */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["errorResponse"];
                };
            };
            default: components["responses"]["serverError"];
        };
    };
    saveContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: components["parameters"]["filename"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                    expectedHash: string;
                    expectedOrderVersion: string;
                };
            };
        };
        responses: {
            200: components["responses"]["freshBoard"];
            409: components["responses"]["conflict"];
            default: components["responses"]["serverError"];
        };
    };
    transitionItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: components["parameters"]["filename"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    state: components["schemas"]["state"];
                    expectedHash: string;
                    expectedOrderVersion: string;
                    /** @description index into the destination lane's ranked list only, never the displayed card sequence. */
                    position?: number;
                };
            };
        };
        responses: {
            200: components["responses"]["freshBoard"];
            409: components["responses"]["conflict"];
            default: components["responses"]["serverError"];
        };
    };
    reorderLane: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lane: components["schemas"]["state"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description only the resulting ranked prefix, never the whole displayed lane; cards absent from it stay unranked. */
                    filenames: string[];
                    expectedVersion: string;
                };
            };
        };
        responses: {
            200: components["responses"]["freshBoard"];
            409: components["responses"]["conflict"];
            default: components["responses"]["serverError"];
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: components["parameters"]["filename"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedHash: string;
                    expectedOrderVersion: string;
                };
            };
        };
        responses: {
            200: components["responses"]["freshBoard"];
            409: components["responses"]["conflict"];
            default: components["responses"]["serverError"];
        };
    };
    retitleItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: components["parameters"]["filename"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    expectedHash: string;
                    expectedOrderVersion: string;
                };
            };
        };
        responses: {
            /** @description retitled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["itemLanded"];
                };
            };
            400: components["responses"]["validationError"];
            409: components["responses"]["conflict"];
            default: components["responses"]["serverError"];
        };
    };
    renameToSlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: components["parameters"]["filename"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedHash: string;
                    expectedOrderVersion: string;
                };
            };
        };
        responses: {
            /** @description renamed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["itemLanded"];
                };
            };
            400: components["responses"]["validationError"];
            409: components["responses"]["conflict"];
            default: components["responses"]["serverError"];
        };
    };
}
