// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateItem implements createItem operation.
	//
	// Capture a new item into inbox.
	//
	// POST /items
	CreateItem(ctx context.Context, req *CreateItemReq) (CreateItemRes, error)
	// GetBoard implements getBoard operation.
	//
	// The computed board, rebuilt from a fresh read of the disk.
	//
	// GET /board
	GetBoard(ctx context.Context) (*Board, error)
	// GetItem implements getItem operation.
	//
	// One item's raw content and parsed card.
	//
	// GET /items/{filename}
	GetItem(ctx context.Context, params GetItemParams) (GetItemRes, error)
	// RenameToSlug implements renameToSlug operation.
	//
	// Repair the filename-mismatch flag with one rename.
	//
	// POST /items/{filename}/rename-to-slug
	RenameToSlug(ctx context.Context, req *RenameToSlugReq, params RenameToSlugParams) (RenameToSlugRes, error)
	// ReorderLane implements reorderLane operation.
	//
	// Rewrite one lane's ranked prefix.
	//
	// PUT /order/{lane}
	ReorderLane(ctx context.Context, req *ReorderLaneReq, params ReorderLaneParams) (ReorderLaneRes, error)
	// RetitleItem implements retitleItem operation.
	//
	// Retitle and rename to the new slug, rank preserved.
	//
	// POST /items/{filename}/retitle
	RetitleItem(ctx context.Context, req *RetitleItemReq, params RetitleItemParams) (RetitleItemRes, error)
	// SaveContent implements saveContent operation.
	//
	// Raw save; a state-changing save runs the ranked-transition cleanup.
	//
	// PUT /items/{filename}/content
	SaveContent(ctx context.Context, req *SaveContentReq, params SaveContentParams) (SaveContentRes, error)
	// TransitionItem implements transitionItem operation.
	//
	// Transition, or transition-and-place when position is given.
	//
	// POST /items/{filename}/state
	TransitionItem(ctx context.Context, req *TransitionItemReq, params TransitionItemParams) (TransitionItemRes, error)
	// NewError creates *ServerErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ServerErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
