// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateItem implements createItem operation.
//
// Capture a new item into inbox.
//
// POST /items
func (UnimplementedHandler) CreateItem(ctx context.Context, req *CreateItemReq) (r CreateItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteItem implements deleteItem operation.
//
// Remove an item file — the operator's explicit curation gesture. the item's order.yaml entries go
// in the same gesture.
//
// POST /items/{filename}/delete
func (UnimplementedHandler) DeleteItem(ctx context.Context, req *DeleteItemReq, params DeleteItemParams) (r DeleteItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBoard implements getBoard operation.
//
// The computed board, rebuilt from a fresh read of the disk.
//
// GET /board
func (UnimplementedHandler) GetBoard(ctx context.Context) (r *Board, _ error) {
	return r, ht.ErrNotImplemented
}

// GetItem implements getItem operation.
//
// One item's raw content and parsed card.
//
// GET /items/{filename}
func (UnimplementedHandler) GetItem(ctx context.Context, params GetItemParams) (r GetItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RenameToSlug implements renameToSlug operation.
//
// Repair the filename-mismatch flag with one rename.
//
// POST /items/{filename}/rename-to-slug
func (UnimplementedHandler) RenameToSlug(ctx context.Context, req *RenameToSlugReq, params RenameToSlugParams) (r RenameToSlugRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReorderLane implements reorderLane operation.
//
// Rewrite one lane's ranked prefix.
//
// PUT /order/{lane}
func (UnimplementedHandler) ReorderLane(ctx context.Context, req *ReorderLaneReq, params ReorderLaneParams) (r ReorderLaneRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RetitleItem implements retitleItem operation.
//
// Retitle and rename to the new slug, rank preserved.
//
// POST /items/{filename}/retitle
func (UnimplementedHandler) RetitleItem(ctx context.Context, req *RetitleItemReq, params RetitleItemParams) (r RetitleItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SaveContent implements saveContent operation.
//
// Raw save; a state-changing save runs the ranked-transition cleanup.
//
// PUT /items/{filename}/content
func (UnimplementedHandler) SaveContent(ctx context.Context, req *SaveContentReq, params SaveContentParams) (r SaveContentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchItems implements searchItems operation.
//
// Case-insensitive substring search over item titles and bodies, against a fresh read of the disk.
//
// GET /search
func (UnimplementedHandler) SearchItems(ctx context.Context, params SearchItemsParams) (r *SearchItemsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// TransitionItem implements transitionItem operation.
//
// Transition, or transition-and-place when position is given.
//
// POST /items/{filename}/state
func (UnimplementedHandler) TransitionItem(ctx context.Context, req *TransitionItemReq, params TransitionItemParams) (r TransitionItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ServerErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ServerErrorStatusCode) {
	r = new(ServerErrorStatusCode)
	return r
}
