// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"

	"github.com/go-faster/errors"
)

func (s *ServerErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/board
type Board struct {
	// The discovered workspace root's name.
	Project string `json:"project"`
	Lanes   []Lane `json:"lanes"`
	// Order.yaml's hash, or the sentinel "absent". absence is a version.
	OrderVersion string `json:"orderVersion"`
}

// GetProject returns the value of Project.
func (s *Board) GetProject() string {
	return s.Project
}

// GetLanes returns the value of Lanes.
func (s *Board) GetLanes() []Lane {
	return s.Lanes
}

// GetOrderVersion returns the value of OrderVersion.
func (s *Board) GetOrderVersion() string {
	return s.OrderVersion
}

// SetProject sets the value of Project.
func (s *Board) SetProject(val string) {
	s.Project = val
}

// SetLanes sets the value of Lanes.
func (s *Board) SetLanes(val []Lane) {
	s.Lanes = val
}

// SetOrderVersion sets the value of OrderVersion.
func (s *Board) SetOrderVersion(val string) {
	s.OrderVersion = val
}

func (*Board) deleteItemRes()     {}
func (*Board) reorderLaneRes()    {}
func (*Board) saveContentRes()    {}
func (*Board) transitionItemRes() {}

// Ref: #/components/schemas/card
type Card struct {
	Filename string `json:"filename"`
	// Empty when the title could not be read; show the filename.
	Title string `json:"title"`
	// Absent when state could not be read; the lane carries the effective placement.
	State   OptState  `json:"state"`
	Created OptString `json:"created"`
	Tags    []string  `json:"tags"`
	// Parts of the stack this item impacts; most projects don't use them.
	Subsystems []string   `json:"subsystems"`
	Source     OptString  `json:"source"`
	Milestone  OptString  `json:"milestone"`
	Log        []LogEntry `json:"log"`
	Flags      []Flag     `json:"flags"`
	Hash       string     `json:"hash"`
}

// GetFilename returns the value of Filename.
func (s *Card) GetFilename() string {
	return s.Filename
}

// GetTitle returns the value of Title.
func (s *Card) GetTitle() string {
	return s.Title
}

// GetState returns the value of State.
func (s *Card) GetState() OptState {
	return s.State
}

// GetCreated returns the value of Created.
func (s *Card) GetCreated() OptString {
	return s.Created
}

// GetTags returns the value of Tags.
func (s *Card) GetTags() []string {
	return s.Tags
}

// GetSubsystems returns the value of Subsystems.
func (s *Card) GetSubsystems() []string {
	return s.Subsystems
}

// GetSource returns the value of Source.
func (s *Card) GetSource() OptString {
	return s.Source
}

// GetMilestone returns the value of Milestone.
func (s *Card) GetMilestone() OptString {
	return s.Milestone
}

// GetLog returns the value of Log.
func (s *Card) GetLog() []LogEntry {
	return s.Log
}

// GetFlags returns the value of Flags.
func (s *Card) GetFlags() []Flag {
	return s.Flags
}

// GetHash returns the value of Hash.
func (s *Card) GetHash() string {
	return s.Hash
}

// SetFilename sets the value of Filename.
func (s *Card) SetFilename(val string) {
	s.Filename = val
}

// SetTitle sets the value of Title.
func (s *Card) SetTitle(val string) {
	s.Title = val
}

// SetState sets the value of State.
func (s *Card) SetState(val OptState) {
	s.State = val
}

// SetCreated sets the value of Created.
func (s *Card) SetCreated(val OptString) {
	s.Created = val
}

// SetTags sets the value of Tags.
func (s *Card) SetTags(val []string) {
	s.Tags = val
}

// SetSubsystems sets the value of Subsystems.
func (s *Card) SetSubsystems(val []string) {
	s.Subsystems = val
}

// SetSource sets the value of Source.
func (s *Card) SetSource(val OptString) {
	s.Source = val
}

// SetMilestone sets the value of Milestone.
func (s *Card) SetMilestone(val OptString) {
	s.Milestone = val
}

// SetLog sets the value of Log.
func (s *Card) SetLog(val []LogEntry) {
	s.Log = val
}

// SetFlags sets the value of Flags.
func (s *Card) SetFlags(val []Flag) {
	s.Flags = val
}

// SetHash sets the value of Hash.
func (s *Card) SetHash(val string) {
	s.Hash = val
}

// Ref: #/components/schemas/conflict
type Conflict struct {
	Reason  ConflictReason `json:"reason"`
	Message string         `json:"message"`
	// Capture collisions; the preserved .capture- draft.
	TempPath OptString `json:"tempPath"`
	// Retitle and rename collisions; the surviving source file.
	SourcePath OptString `json:"sourcePath"`
	// The colliding destination.
	DestPath OptString `json:"destPath"`
}

// GetReason returns the value of Reason.
func (s *Conflict) GetReason() ConflictReason {
	return s.Reason
}

// GetMessage returns the value of Message.
func (s *Conflict) GetMessage() string {
	return s.Message
}

// GetTempPath returns the value of TempPath.
func (s *Conflict) GetTempPath() OptString {
	return s.TempPath
}

// GetSourcePath returns the value of SourcePath.
func (s *Conflict) GetSourcePath() OptString {
	return s.SourcePath
}

// GetDestPath returns the value of DestPath.
func (s *Conflict) GetDestPath() OptString {
	return s.DestPath
}

// SetReason sets the value of Reason.
func (s *Conflict) SetReason(val ConflictReason) {
	s.Reason = val
}

// SetMessage sets the value of Message.
func (s *Conflict) SetMessage(val string) {
	s.Message = val
}

// SetTempPath sets the value of TempPath.
func (s *Conflict) SetTempPath(val OptString) {
	s.TempPath = val
}

// SetSourcePath sets the value of SourcePath.
func (s *Conflict) SetSourcePath(val OptString) {
	s.SourcePath = val
}

// SetDestPath sets the value of DestPath.
func (s *Conflict) SetDestPath(val OptString) {
	s.DestPath = val
}

func (*Conflict) createItemRes()     {}
func (*Conflict) deleteItemRes()     {}
func (*Conflict) renameToSlugRes()   {}
func (*Conflict) reorderLaneRes()    {}
func (*Conflict) retitleItemRes()    {}
func (*Conflict) saveContentRes()    {}
func (*Conflict) transitionItemRes() {}

type ConflictReason string

const (
	ConflictReasonItemConflict  ConflictReason = "item_conflict"
	ConflictReasonOrderConflict ConflictReason = "order_conflict"
	ConflictReasonSlugCollision ConflictReason = "slug_collision"
)

// AllValues returns all ConflictReason values.
func (ConflictReason) AllValues() []ConflictReason {
	return []ConflictReason{
		ConflictReasonItemConflict,
		ConflictReasonOrderConflict,
		ConflictReasonSlugCollision,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ConflictReason) MarshalText() ([]byte, error) {
	switch s {
	case ConflictReasonItemConflict:
		return []byte(s), nil
	case ConflictReasonOrderConflict:
		return []byte(s), nil
	case ConflictReasonSlugCollision:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ConflictReason) UnmarshalText(data []byte) error {
	switch ConflictReason(data) {
	case ConflictReasonItemConflict:
		*s = ConflictReasonItemConflict
		return nil
	case ConflictReasonOrderConflict:
		*s = ConflictReasonOrderConflict
		return nil
	case ConflictReasonSlugCollision:
		*s = ConflictReasonSlugCollision
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateItemReq struct {
	Title string    `json:"title"`
	Body  OptString `json:"body"`
}

// GetTitle returns the value of Title.
func (s *CreateItemReq) GetTitle() string {
	return s.Title
}

// GetBody returns the value of Body.
func (s *CreateItemReq) GetBody() OptString {
	return s.Body
}

// SetTitle sets the value of Title.
func (s *CreateItemReq) SetTitle(val string) {
	s.Title = val
}

// SetBody sets the value of Body.
func (s *CreateItemReq) SetBody(val OptString) {
	s.Body = val
}

type DeleteItemReq struct {
	ExpectedHash         string `json:"expectedHash"`
	ExpectedOrderVersion string `json:"expectedOrderVersion"`
}

// GetExpectedHash returns the value of ExpectedHash.
func (s *DeleteItemReq) GetExpectedHash() string {
	return s.ExpectedHash
}

// GetExpectedOrderVersion returns the value of ExpectedOrderVersion.
func (s *DeleteItemReq) GetExpectedOrderVersion() string {
	return s.ExpectedOrderVersion
}

// SetExpectedHash sets the value of ExpectedHash.
func (s *DeleteItemReq) SetExpectedHash(val string) {
	s.ExpectedHash = val
}

// SetExpectedOrderVersion sets the value of ExpectedOrderVersion.
func (s *DeleteItemReq) SetExpectedOrderVersion(val string) {
	s.ExpectedOrderVersion = val
}

// Ref: #/components/schemas/errorResponse
type ErrorResponse struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

func (*ErrorResponse) createItemRes()   {}
func (*ErrorResponse) getItemRes()      {}
func (*ErrorResponse) renameToSlugRes() {}
func (*ErrorResponse) retitleItemRes()  {}

// Ref: #/components/schemas/flag
type Flag struct {
	Kind       FlagKind `json:"kind"`
	Diagnostic string   `json:"diagnostic"`
}

// GetKind returns the value of Kind.
func (s *Flag) GetKind() FlagKind {
	return s.Kind
}

// GetDiagnostic returns the value of Diagnostic.
func (s *Flag) GetDiagnostic() string {
	return s.Diagnostic
}

// SetKind sets the value of Kind.
func (s *Flag) SetKind(val FlagKind) {
	s.Kind = val
}

// SetDiagnostic sets the value of Diagnostic.
func (s *Flag) SetDiagnostic(val string) {
	s.Diagnostic = val
}

type FlagKind string

const (
	FlagKindMalformed        FlagKind = "malformed"
	FlagKindFilenameMismatch FlagKind = "filename-mismatch"
)

// AllValues returns all FlagKind values.
func (FlagKind) AllValues() []FlagKind {
	return []FlagKind{
		FlagKindMalformed,
		FlagKindFilenameMismatch,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s FlagKind) MarshalText() ([]byte, error) {
	switch s {
	case FlagKindMalformed:
		return []byte(s), nil
	case FlagKindFilenameMismatch:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *FlagKind) UnmarshalText(data []byte) error {
	switch FlagKind(data) {
	case FlagKindMalformed:
		*s = FlagKindMalformed
		return nil
	case FlagKindFilenameMismatch:
		*s = FlagKindFilenameMismatch
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type GetItemOK struct {
	Content string `json:"content"`
	Card    Card   `json:"card"`
	Hash    string `json:"hash"`
}

// GetContent returns the value of Content.
func (s *GetItemOK) GetContent() string {
	return s.Content
}

// GetCard returns the value of Card.
func (s *GetItemOK) GetCard() Card {
	return s.Card
}

// GetHash returns the value of Hash.
func (s *GetItemOK) GetHash() string {
	return s.Hash
}

// SetContent sets the value of Content.
func (s *GetItemOK) SetContent(val string) {
	s.Content = val
}

// SetCard sets the value of Card.
func (s *GetItemOK) SetCard(val Card) {
	s.Card = val
}

// SetHash sets the value of Hash.
func (s *GetItemOK) SetHash(val string) {
	s.Hash = val
}

func (*GetItemOK) getItemRes() {}

// Ref: #/components/schemas/itemLanded
type ItemLanded struct {
	Filename string `json:"filename"`
	Board    Board  `json:"board"`
}

// GetFilename returns the value of Filename.
func (s *ItemLanded) GetFilename() string {
	return s.Filename
}

// GetBoard returns the value of Board.
func (s *ItemLanded) GetBoard() Board {
	return s.Board
}

// SetFilename sets the value of Filename.
func (s *ItemLanded) SetFilename(val string) {
	s.Filename = val
}

// SetBoard sets the value of Board.
func (s *ItemLanded) SetBoard(val Board) {
	s.Board = val
}

func (*ItemLanded) createItemRes()   {}
func (*ItemLanded) renameToSlugRes() {}
func (*ItemLanded) retitleItemRes()  {}

// Ref: #/components/schemas/lane
type Lane struct {
	State State  `json:"state"`
	Cards []Card `json:"cards"`
	// The first rankedCount cards are the lane's ranked prefix; the rest are the computed unranked tail.
	RankedCount int `json:"rankedCount"`
}

// GetState returns the value of State.
func (s *Lane) GetState() State {
	return s.State
}

// GetCards returns the value of Cards.
func (s *Lane) GetCards() []Card {
	return s.Cards
}

// GetRankedCount returns the value of RankedCount.
func (s *Lane) GetRankedCount() int {
	return s.RankedCount
}

// SetState sets the value of State.
func (s *Lane) SetState(val State) {
	s.State = val
}

// SetCards sets the value of Cards.
func (s *Lane) SetCards(val []Card) {
	s.Cards = val
}

// SetRankedCount sets the value of RankedCount.
func (s *Lane) SetRankedCount(val int) {
	s.RankedCount = val
}

// Ref: #/components/schemas/logEntry
type LogEntry struct {
	Stamp string `json:"stamp"`
	Note  string `json:"note"`
}

// GetStamp returns the value of Stamp.
func (s *LogEntry) GetStamp() string {
	return s.Stamp
}

// GetNote returns the value of Note.
func (s *LogEntry) GetNote() string {
	return s.Note
}

// SetStamp sets the value of Stamp.
func (s *LogEntry) SetStamp(val string) {
	s.Stamp = val
}

// SetNote sets the value of Note.
func (s *LogEntry) SetNote(val string) {
	s.Note = val
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptState returns new OptState with value set to v.
func NewOptState(v State) OptState {
	return OptState{
		Value: v,
		Set:   true,
	}
}

// OptState is optional State.
type OptState struct {
	Value State
	Set   bool
}

// IsSet returns true if OptState was set.
func (o OptState) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptState) Reset() {
	var v State
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptState) SetTo(v State) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptState) Get() (v State, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptState) Or(d State) State {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type RenameToSlugReq struct {
	ExpectedHash         string `json:"expectedHash"`
	ExpectedOrderVersion string `json:"expectedOrderVersion"`
}

// GetExpectedHash returns the value of ExpectedHash.
func (s *RenameToSlugReq) GetExpectedHash() string {
	return s.ExpectedHash
}

// GetExpectedOrderVersion returns the value of ExpectedOrderVersion.
func (s *RenameToSlugReq) GetExpectedOrderVersion() string {
	return s.ExpectedOrderVersion
}

// SetExpectedHash sets the value of ExpectedHash.
func (s *RenameToSlugReq) SetExpectedHash(val string) {
	s.ExpectedHash = val
}

// SetExpectedOrderVersion sets the value of ExpectedOrderVersion.
func (s *RenameToSlugReq) SetExpectedOrderVersion(val string) {
	s.ExpectedOrderVersion = val
}

type ReorderLaneReq struct {
	// Only the resulting ranked prefix, never the whole displayed lane; cards absent from it stay
	// unranked.
	Filenames       []string `json:"filenames"`
	ExpectedVersion string   `json:"expectedVersion"`
}

// GetFilenames returns the value of Filenames.
func (s *ReorderLaneReq) GetFilenames() []string {
	return s.Filenames
}

// GetExpectedVersion returns the value of ExpectedVersion.
func (s *ReorderLaneReq) GetExpectedVersion() string {
	return s.ExpectedVersion
}

// SetFilenames sets the value of Filenames.
func (s *ReorderLaneReq) SetFilenames(val []string) {
	s.Filenames = val
}

// SetExpectedVersion sets the value of ExpectedVersion.
func (s *ReorderLaneReq) SetExpectedVersion(val string) {
	s.ExpectedVersion = val
}

type RetitleItemReq struct {
	Title                string `json:"title"`
	ExpectedHash         string `json:"expectedHash"`
	ExpectedOrderVersion string `json:"expectedOrderVersion"`
}

// GetTitle returns the value of Title.
func (s *RetitleItemReq) GetTitle() string {
	return s.Title
}

// GetExpectedHash returns the value of ExpectedHash.
func (s *RetitleItemReq) GetExpectedHash() string {
	return s.ExpectedHash
}

// GetExpectedOrderVersion returns the value of ExpectedOrderVersion.
func (s *RetitleItemReq) GetExpectedOrderVersion() string {
	return s.ExpectedOrderVersion
}

// SetTitle sets the value of Title.
func (s *RetitleItemReq) SetTitle(val string) {
	s.Title = val
}

// SetExpectedHash sets the value of ExpectedHash.
func (s *RetitleItemReq) SetExpectedHash(val string) {
	s.ExpectedHash = val
}

// SetExpectedOrderVersion sets the value of ExpectedOrderVersion.
func (s *RetitleItemReq) SetExpectedOrderVersion(val string) {
	s.ExpectedOrderVersion = val
}

type SaveContentReq struct {
	Content              string `json:"content"`
	ExpectedHash         string `json:"expectedHash"`
	ExpectedOrderVersion string `json:"expectedOrderVersion"`
}

// GetContent returns the value of Content.
func (s *SaveContentReq) GetContent() string {
	return s.Content
}

// GetExpectedHash returns the value of ExpectedHash.
func (s *SaveContentReq) GetExpectedHash() string {
	return s.ExpectedHash
}

// GetExpectedOrderVersion returns the value of ExpectedOrderVersion.
func (s *SaveContentReq) GetExpectedOrderVersion() string {
	return s.ExpectedOrderVersion
}

// SetContent sets the value of Content.
func (s *SaveContentReq) SetContent(val string) {
	s.Content = val
}

// SetExpectedHash sets the value of ExpectedHash.
func (s *SaveContentReq) SetExpectedHash(val string) {
	s.ExpectedHash = val
}

// SetExpectedOrderVersion sets the value of ExpectedOrderVersion.
func (s *SaveContentReq) SetExpectedOrderVersion(val string) {
	s.ExpectedOrderVersion = val
}

// ServerErrorStatusCode wraps ErrorResponse with StatusCode.
type ServerErrorStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ServerErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ServerErrorStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ServerErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ServerErrorStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// Ref: #/components/schemas/state
type State string

const (
	StateInbox       State = "inbox"
	StateHorizon     State = "horizon"
	StateResearching State = "researching"
	StateBuilding    State = "building"
	StateEvaluating  State = "evaluating"
	StateDone        State = "done"
	StateDropped     State = "dropped"
)

// AllValues returns all State values.
func (State) AllValues() []State {
	return []State{
		StateInbox,
		StateHorizon,
		StateResearching,
		StateBuilding,
		StateEvaluating,
		StateDone,
		StateDropped,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s State) MarshalText() ([]byte, error) {
	switch s {
	case StateInbox:
		return []byte(s), nil
	case StateHorizon:
		return []byte(s), nil
	case StateResearching:
		return []byte(s), nil
	case StateBuilding:
		return []byte(s), nil
	case StateEvaluating:
		return []byte(s), nil
	case StateDone:
		return []byte(s), nil
	case StateDropped:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *State) UnmarshalText(data []byte) error {
	switch State(data) {
	case StateInbox:
		*s = StateInbox
		return nil
	case StateHorizon:
		*s = StateHorizon
		return nil
	case StateResearching:
		*s = StateResearching
		return nil
	case StateBuilding:
		*s = StateBuilding
		return nil
	case StateEvaluating:
		*s = StateEvaluating
		return nil
	case StateDone:
		*s = StateDone
		return nil
	case StateDropped:
		*s = StateDropped
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type TransitionItemReq struct {
	State                State  `json:"state"`
	ExpectedHash         string `json:"expectedHash"`
	ExpectedOrderVersion string `json:"expectedOrderVersion"`
	// Index into the destination lane's ranked list only, never the displayed card sequence.
	Position OptInt `json:"position"`
}

// GetState returns the value of State.
func (s *TransitionItemReq) GetState() State {
	return s.State
}

// GetExpectedHash returns the value of ExpectedHash.
func (s *TransitionItemReq) GetExpectedHash() string {
	return s.ExpectedHash
}

// GetExpectedOrderVersion returns the value of ExpectedOrderVersion.
func (s *TransitionItemReq) GetExpectedOrderVersion() string {
	return s.ExpectedOrderVersion
}

// GetPosition returns the value of Position.
func (s *TransitionItemReq) GetPosition() OptInt {
	return s.Position
}

// SetState sets the value of State.
func (s *TransitionItemReq) SetState(val State) {
	s.State = val
}

// SetExpectedHash sets the value of ExpectedHash.
func (s *TransitionItemReq) SetExpectedHash(val string) {
	s.ExpectedHash = val
}

// SetExpectedOrderVersion sets the value of ExpectedOrderVersion.
func (s *TransitionItemReq) SetExpectedOrderVersion(val string) {
	s.ExpectedOrderVersion = val
}

// SetPosition sets the value of Position.
func (s *TransitionItemReq) SetPosition(val OptInt) {
	s.Position = val
}
