// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteItemParams is parameters of deleteItem operation.
type DeleteItemParams struct {
	Filename string
}

func unpackDeleteItemParams(packed middleware.Parameters) (params DeleteItemParams) {
	{
		key := middleware.ParameterKey{
			Name: "filename",
			In:   "path",
		}
		params.Filename = packed[key].(string)
	}
	return params
}

func decodeDeleteItemParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteItemParams, _ error) {
	// Decode path: filename.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "filename",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Filename = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "filename",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetItemParams is parameters of getItem operation.
type GetItemParams struct {
	Filename string
}

func unpackGetItemParams(packed middleware.Parameters) (params GetItemParams) {
	{
		key := middleware.ParameterKey{
			Name: "filename",
			In:   "path",
		}
		params.Filename = packed[key].(string)
	}
	return params
}

func decodeGetItemParams(args [1]string, argsEscaped bool, r *http.Request) (params GetItemParams, _ error) {
	// Decode path: filename.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "filename",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Filename = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "filename",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// RenameToSlugParams is parameters of renameToSlug operation.
type RenameToSlugParams struct {
	Filename string
}

func unpackRenameToSlugParams(packed middleware.Parameters) (params RenameToSlugParams) {
	{
		key := middleware.ParameterKey{
			Name: "filename",
			In:   "path",
		}
		params.Filename = packed[key].(string)
	}
	return params
}

func decodeRenameToSlugParams(args [1]string, argsEscaped bool, r *http.Request) (params RenameToSlugParams, _ error) {
	// Decode path: filename.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "filename",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Filename = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "filename",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ReorderLaneParams is parameters of reorderLane operation.
type ReorderLaneParams struct {
	Lane State
}

func unpackReorderLaneParams(packed middleware.Parameters) (params ReorderLaneParams) {
	{
		key := middleware.ParameterKey{
			Name: "lane",
			In:   "path",
		}
		params.Lane = packed[key].(State)
	}
	return params
}

func decodeReorderLaneParams(args [1]string, argsEscaped bool, r *http.Request) (params ReorderLaneParams, _ error) {
	// Decode path: lane.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "lane",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Lane = State(c)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.Lane.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "lane",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// RetitleItemParams is parameters of retitleItem operation.
type RetitleItemParams struct {
	Filename string
}

func unpackRetitleItemParams(packed middleware.Parameters) (params RetitleItemParams) {
	{
		key := middleware.ParameterKey{
			Name: "filename",
			In:   "path",
		}
		params.Filename = packed[key].(string)
	}
	return params
}

func decodeRetitleItemParams(args [1]string, argsEscaped bool, r *http.Request) (params RetitleItemParams, _ error) {
	// Decode path: filename.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "filename",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Filename = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "filename",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SaveContentParams is parameters of saveContent operation.
type SaveContentParams struct {
	Filename string
}

func unpackSaveContentParams(packed middleware.Parameters) (params SaveContentParams) {
	{
		key := middleware.ParameterKey{
			Name: "filename",
			In:   "path",
		}
		params.Filename = packed[key].(string)
	}
	return params
}

func decodeSaveContentParams(args [1]string, argsEscaped bool, r *http.Request) (params SaveContentParams, _ error) {
	// Decode path: filename.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "filename",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Filename = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "filename",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SearchItemsParams is parameters of searchItems operation.
type SearchItemsParams struct {
	Q string
}

func unpackSearchItemsParams(packed middleware.Parameters) (params SearchItemsParams) {
	{
		key := middleware.ParameterKey{
			Name: "q",
			In:   "query",
		}
		params.Q = packed[key].(string)
	}
	return params
}

func decodeSearchItemsParams(args [0]string, argsEscaped bool, r *http.Request) (params SearchItemsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: q.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "q",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Q = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.Q)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "q",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// TransitionItemParams is parameters of transitionItem operation.
type TransitionItemParams struct {
	Filename string
}

func unpackTransitionItemParams(packed middleware.Parameters) (params TransitionItemParams) {
	{
		key := middleware.ParameterKey{
			Name: "filename",
			In:   "path",
		}
		params.Filename = packed[key].(string)
	}
	return params
}

func decodeTransitionItemParams(args [1]string, argsEscaped bool, r *http.Request) (params TransitionItemParams, _ error) {
	// Decode path: filename.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "filename",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Filename = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "filename",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
