// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateItemOperation     OperationName = "CreateItem"
	DeleteItemOperation     OperationName = "DeleteItem"
	GetBoardOperation       OperationName = "GetBoard"
	GetItemOperation        OperationName = "GetItem"
	RenameToSlugOperation   OperationName = "RenameToSlug"
	ReorderLaneOperation    OperationName = "ReorderLane"
	RetitleItemOperation    OperationName = "RetitleItem"
	SaveContentOperation    OperationName = "SaveContent"
	SearchItemsOperation    OperationName = "SearchItems"
	TransitionItemOperation OperationName = "TransitionItem"
)
